### ISSUE TITLE
"folderPath" options do not work 

### ISSUE THREAD

**Issue by mustique** [pupunzi/jquery.mb.bgndGallery#3]
Hello Matteo,

even if the gallery is running on my mamp-pro web-server, the "folderPath" options do not work.
The page shows no photos. 

This is only happen with the actual versions which can be downloaded via GitHub.
It on the "demo.html" and the "demo_lookUp.html" files.

When I tested yesterday the "demo.html" version which I downloaded from your website, 
the "folderPath" option works like charm ... no problem ...

Could you pleas check and fix this?

Kind regards,
Martin

**Comment by pupunzi** [comment]
Hi Martin,
Just fixed this issue introduced in with the last release.

You can download the 1.9.1 version that should work fine.

**Comment by mustique** [comment]
WOW ... thank you so much for your fast reply and fixing the code !!!
Yeah, its working now perfect!

Thank you so much! 
Really appreciate your kind and fast help!

Have a nice neekend, 
Martin
