### ISSUE TITLE
add dist for each tag

### ISSUE THREAD

**Issue by maruilian11** [pupunzi/jquery.mb.bgndGallery#4]
hi, recently we want to add your lib on https://cdnjs.com, could you please add dist folder for every tag so that we can add pre-versions and later versions with **git auto-update**.
or if there is npm package url of this lib, we'll be glad to use npm auto update.
thank you very much!

https://github.com/cdnjs/cdnjs/issues/6952

**Comment by maruilian11** [comment]
sorry, didn't notice 1.9.1 is already there.

**Comment by pupunzi** [comment]
the npm package: https://www.npmjs.com/package/jquery.mb.bgndgallery

**Comment by maruilian11** [comment]
is it possible to use `dist` folder in npm package?
thank you very much!

**Comment by pupunzi** [comment]
With the next version update it will be: 

"main": "dist/jquery.mb.bgndGallery.min.js"

**Comment by maruilian11** [comment]
got it! thank you!

**Comment by maruilian11** [comment]
hi @pupunzi,
i saw `v1.9.2` has been released on github, how long does it probably take to be on npm? thanks!
