### ISSUE TITLE
There is an error including it in Joomla

### ISSUE THREAD

**Issue by Maofree** [pupunzi/jquery.mb.bgndGallery#5]
Hi
I try to add your plugin inside a site made with joomla
but I get an error

TypeError: d is undefined

![1111](https://cloud.githubusercontent.com/assets/653230/16738611/bb05f114-4796-11e6-8575-7a6438331e24.png)

the css and js files are uploaded correctly

thanks

**Comment by pupunzi** [comment]
Do you have an URLto the page  where this issue happens?

**Comment by maofree** [comment]
Hi
http://maofree.changeip.net/travaglio/osteria-gelateria/
at first login set two times "maofree"

thanks
